In [10]:
import pandas as pd
from matplotlib import pyplot
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Imputer
%matplotlib inline

In [13]:
#Load data
df_test = pd.read_csv("test.csv")

In [15]:
df_test_bidid = df_test['bidid']
df_test_bidid.to_pickle('df_test_bidid')
df_test = df_test.drop(['urlid','bidid', 'userid'], axis = 1)

In [16]:
# Check for null in df 

df_test_cols = list(df_test)
for col_name in df_test_cols:
    print(col_name, df_test[col_name].isnull().values.any())

weekday False
hour False
useragent False
IP False
region False
city False
adexchange True
domain True
url True
slotid False
slotwidth False
slotheight False
slotvisibility False
slotformat False
slotprice False
creative False
keypage True
advertiser False
usertag True

In [17]:
# Fill null as 'unknown' 
df_test['url'].fillna('unknown', inplace = True)
df_test['keypage'].fillna('unknown', inplace = True)
df_test['usertag'].fillna('unknown', inplace = True)

# Convert adexchange data type to int 
df_test['adexchange'].fillna(0 , inplace = True )
df_test.adexchange =  df_test.adexchange.astype(int)

# Convert domain data type 
df_test.domain = df_test.domain.astype(str)

# Check for null in df again
col_names = list(df_test)
for column in col_names:
    print(column, df_test[column].isnull().values.any())

weekday False
hour False
useragent False
IP False
region False
city False
adexchange False
domain False
url False
slotid False
slotwidth False
slotheight False
slotvisibility False
slotformat False
slotprice False
creative False
keypage False
advertiser False
usertag False

In [18]:
lb_encode = LabelEncoder()

test_cat_cols = ['useragent','IP','url','domain','slotid','slotvisibility','slotformat','creative','keypage','usertag']
for cat_name in test_cat_cols:
    print('endcoding', cat_name, '.....')
    df_test[cat_name + '_encoded'] = lb_encode.fit_transform(df_test[cat_name])

print()
print('Encoding done!')

endcoding useragent .....
endcoding IP .....
endcoding url .....
endcoding domain .....
endcoding slotid .....
endcoding slotvisibility .....
endcoding slotformat .....
endcoding creative .....
endcoding keypage .....
endcoding usertag .....

Encoding done!

In [20]:
df_test_prepared = df_test.drop(columns = ['useragent','IP','domain','url','slotid','slotvisibility','slotformat','creative','keypage','usertag'])

# Save prepared df 
df_test_prepared.to_pickle('df_test_prepared')

df_test_prepared.head()

,weekday,hour,region,city,adexchange,slotwidth,slotheight,slotprice,advertiser,useragent_encoded,IP_encoded,url_encoded,domain_encoded,slotid_encoded,slotvisibility_encoded,slotformat_encoded,creative_encoded,keypage_encoded,usertag_encoded
0,0,12,146,159,3,300,250,10,3427,24,167628,18581,3258,13944,0,0,1,11,17374
1,3,14,1,1,0,320,50,5,2997,5,92907,70008,4693,6255,5,3,13,18,115970
2,5,19,27,34,1,336,280,0,1458,26,48596,57287,6951,15499,2,1,89,12,107970
3,0,21,238,245,4,960,90,30,2821,26,46570,27487,2378,3922,5,3,4,18,72990
4,2,20,27,35,3,300,250,50,3386,26,150125,23871,819,14006,0,0,50,3,53930